name: CI
on:
  push:
    branches: [master, ps-harden]
  pull_request:
    # Don't bother running if it's just a script or docs change
    paths-ignore:
      - "bin/**"
      - Dockerfile
      - "*.sh"
      - "*.md"
      - AUTHORS

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  MIX_ENV: test
  V3_URL: ${{ secrets.V3_URL }}
  V3_API_KEY: ${{ secrets.V3_API_KEY }}

jobs:
  # Report file changes by extensions
  # Used to determine which tests to run
  file_changes:
    name: File changes
    uses: ./.github/workflows/changed-files.yml
    with:
      # If it's a Dependabot PR, or a push to master, we want to run every test
      force: ${{ github.event_name == 'push' || contains(github.head_ref, 'dependabot/hex') || contains(github.head_ref, 'dependabot/npm_and_yarn') }}

  tslint:
    name: Linting / TypeScript
    runs-on: ubuntu-20.04
    needs: file_changes
    if: ${{ needs.file_changes.outputs.ts }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-all
    - run: npm run ci:lint:ts

  jslint:
    name: Linting / JavaScript
    runs-on: ubuntu-20.04
    needs: file_changes
    if: ${{ needs.file_changes.outputs.js }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-all
    - run: npm run ci:lint:js

  stylelint:
    name: Linting / CSS
    runs-on: ubuntu-20.04
    needs: file_changes
    if: ${{ needs.file_changes.outputs.scss }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-all
    - run: npm run ci:lint:scss

  elixiraudit:
    name: Auditing / Elixir
    runs-on: ubuntu-20.04
    needs: file_changes
    if: ${{ needs.file_changes.outputs.ex }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-all
    - run: npm run ci:audit:ex

  elixirlint:
    name: Linting / Elixir
    runs-on: ubuntu-20.04
    needs: file_changes
    if: ${{ needs.file_changes.outputs.ex }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-all
    - run: npm run ci:lint:ex

  elixir_unit:
    name: Unit tests / Elixir / --exclude wallaby --cover
    runs-on: ubuntu-20.04
    needs: file_changes
    if: ${{ needs.file_changes.outputs.ex }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/build-app
    - env:
        RECAPTCHA_PUBLIC_KEY: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
        RECAPTCHA_PRIVATE_KEY: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
        OPEN_TRIP_PLANNER_URL: ${{ secrets.OPEN_TRIP_PLANNER_URL }}
      run: npm run ci:unit:exunit
    - name: Upload coverage artifact
      if: ${{ always() && github.event.pull_request }}
      uses: actions/upload-artifact@v2
      with:
        name: Elixir test coverage report
        path: cover/

  js_unit_1:
    name: Unit tests / JavaScript / Mocha
    runs-on: ubuntu-20.04
    needs: file_changes
    if: ${{ needs.file_changes.outputs.js }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-all
    - run: npm run ci:unit:mocha

  js_unit_2:
    name: Unit tests / JavaScript & TypeScript / Jest
    runs-on: ubuntu-20.04
    needs: file_changes
    if: ${{ needs.file_changes.outputs.ts || needs.file_changes.outputs.js }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/build-app
    - run: npm run ci:unit:jest

  type_dialyzer:
    name: Type checks / Elixir
    runs-on: ubuntu-20.04
    needs: file_changes
    if: ${{ needs.file_changes.outputs.ex }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-all
    - uses: mbta/actions/dialyzer@v1

  type_typescript:
    name: Type checks / TypeScript
    runs-on: ubuntu-20.04
    needs: file_changes
    if: ${{ needs.file_changes.outputs.ts }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-all
    - run: npm run ci:types:ts

  elixir_format_check:
    name: Formatting / Elixir
    runs-on: ubuntu-20.04
    needs: file_changes
    if: ${{ needs.file_changes.outputs.ex }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-all
    - run: npm run ci:format:ex

  js_format_check:
    name: Formatting / JavaScript & TypeScript
    runs-on: ubuntu-20.04
    needs: file_changes
    if: ${{ needs.file_changes.outputs.js || needs.file_changes.outputs.ts }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-all
    - run: npm run ci:format:ts

  elixir_wallaby:
    name: Integration tests / Elixir
    runs-on: ubuntu-20.04
    needs: file_changes
    if: ${{ needs.file_changes.outputs.ex }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/build-app
    - run:
        # Install Chromedriver version that corresponds with the version of Chrome that is installed here.
        bash ./scripts/setup_chromedriver.sh
    - env:
        RECAPTCHA_PUBLIC_KEY: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
        RECAPTCHA_PRIVATE_KEY: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
        OPEN_TRIP_PLANNER_URL: ${{ secrets.OPEN_TRIP_PLANNER_URL }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: npm run ci:integration:ex

  cypress:
    name: Integration tests / Cypress
    runs-on: ubuntu-20.04
    needs: file_changes
    if: ${{ needs.file_changes.outputs.ex || needs.file_changes.outputs.js || needs.file_changes.outputs.ts }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/build-app
    - env:
        RECAPTCHA_PUBLIC_KEY: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
        RECAPTCHA_PRIVATE_KEY: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
        OPEN_TRIP_PLANNER_URL: ${{ secrets.OPEN_TRIP_PLANNER_URL }}
      run: npm run ci:integration:cypress
